### ISSUE TITLE
Autocompletion duplicates first characters of line

### ISSUE THREAD

**Issue by FlenkerDLR** [zimfw/bira#1]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

Hello,
When I use the autocompletion feature with the `bira` theme, the first characters will be duplicated and the cursor is misplaced. This only happen, if I need to hit TAB twice. If the word to complete is not ambiguous everything is fine.

The cursor also is misplaced, when the executed command returns an error. For example, when just type `test` or use `Ctrl+C`.

### Steps to reproduce

1. ```
   cd ${$(mktemp -d):A} && \
       ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim && \
       curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh && \
       exec zsh
   ```
2. change theme in `.zimrc` to `bira`
3. Type `echo $P` and hit TAB twice produces:
```
╭─user@machine ~
╰─$ echoecho $PS1
-- parameter --
PAGER              PPID               PROMPT             PROMPT3            PS1                PS3                PSVAR              parameters         path               precmd_functions   prompt           
PATH               PROFILEHOME        PROMPT2            PROMPT4            PS2                PS4                PWD                patchars           pipestatus         preexec_functions  psvar
```
Note the `echoecho` at the beginning
After execution everything I fine again, if command returns without error.

If execution failed, I get:
```
╭─user@machine ~
╰─$                                                                                                                                                                                                127 ↵
  ^
cursor is here
```
So the cursor is inside the `$` and the line behaves more strange.

### Current behavior

The first four characters of the autocompleted line will be duplicated.

When commands execution failed before the input of `npm inst` and TAB twice will produce:
```
╭─user@machine ~
╰─npm innpm install                                                                                                                                                                                                      254 ↵
insta            instal           install          install-ci-test  install-clean    install-test
```
While the cursor is inside the `s` of `install` and `all` is from my history, I think.

### Expected behavior

No duplication of the first characters.
No strange behavior of command line, when use auto completion even after a command failed before.

### zimfw info

```shell
╭─user@machine ~
╰─$ zimfw info
zimfw version:        1.12.1 (built at 2023-09-16 18:25:16 UTC, previous commit is 26151d2)
LANG:                 de_DE.UTF-8
OSTYPE:               linux-gnu
TERM:                 xterm-256color
TERM_PROGRAM:         
TERM_PROGRAM_VERSION: 
ZIM_HOME:             /home/user/.zim
ZSH_VERSION:          5.8
```

### Additional context
Using the theme `steeef` let me use autocompletion as intended.

**Comment by ericbn** [comment]
Hi. Please check https://github.com/zimfw/eriner/issues/3

**Comment by FlenkerDLR** [comment]
Thank you.

So I don't had the right words for my search to find the right answer. But Your link gave me the right direction:
https://stackoverflow.com/a/20953792/12965716

I just had to generate the locale and it worked.
